<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <VersionPrefix>0.8.0</VersionPrefix>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>LagoVista.CloudStorage</AssemblyName>
    <PackageId>LagoVista.CloudStorage</PackageId>
    <PackageTargetFallback Condition=" '$(TargetFramework)' == 'netstandard1.6' ">$(PackageTargetFallback);dnxcore50;portable-net45+win8</PackageTargetFallback>
    <PackageTargetFallback Condition=" '$(TargetFramework)' == 'netcoreapp1.0' ">$(PackageTargetFallback);dnxcore50;portable-net45+win8</PackageTargetFallback>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Properties\**" />
    <EmbeddedResource Remove="Properties\**" />
    <None Remove="Properties\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CassandraCSharpDriver" />
    <PackageReference Include="LagoVista.IoT.Logging" />
    <PackageReference Include="log4net" />
    <PackageReference Include="Microsoft.Azure.Cosmos" />
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="Minio" />
    <PackageReference Include="OpenTelemetry.Api" />
    <PackageReference Include="prometheus-net" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="Azure.Data.Tables" />
    <PackageReference Include="Azure.Storage.Blobs" />
  </ItemGroup>
</Project>
