// <auto-generated />
using System;
using LagoVista.Relational.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LagoVista.Relational.Migrations.Semantic
{
    [DbContext(typeof(SemanticDataContext))]
    [Migration("20260811135942_InitialSemanticCatalog")]
    partial class InitialSemanticCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("App:ProviderName", "Microsoft.EntityFrameworkCore.SqlServer")
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LagoVista.Relational.ArtifactDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(32)")
                        .HasColumnOrder(1);

                    b.Property<string>("ArchetypeKey")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnOrder(10);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2(7)")
                        .HasColumnOrder(13);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnOrder(6);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2(7)")
                        .HasColumnOrder(14);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(4);

                    b.Property<string>("OwnerOrganizationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnOrder(2);

                    b.Property<string>("ProductionCardinalityKey")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnOrder(11);

                    b.Property<string>("PurposeSummary")
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnOrder(7);

                    b.Property<string>("ScopeTypeKey")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnOrder(9);

                    b.Property<string>("SpecificationSha256")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnOrder(12);

                    b.Property<string>("StatusKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(8);

                    b.Property<string>("Tla")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("OwnerOrganizationId")
                        .HasDatabaseName("IX_Artifacts_OwnerOrganizationId");

                    b.HasIndex("OwnerOrganizationId", "ArchetypeKey")
                        .HasDatabaseName("IX_Artifacts_Organization_ArchetypeKey");

                    b.HasIndex("OwnerOrganizationId", "Key")
                        .IsUnique()
                        .HasDatabaseName("UX_Artifacts_Organization_Key");

                    b.HasIndex("OwnerOrganizationId", "ProductionCardinalityKey")
                        .HasDatabaseName("IX_Artifacts_Organization_ProductionCardinalityKey");

                    b.HasIndex("OwnerOrganizationId", "ScopeTypeKey")
                        .HasDatabaseName("IX_Artifacts_Organization_ScopeTypeKey");

                    b.HasIndex("OwnerOrganizationId", "StatusKey")
                        .HasDatabaseName("IX_Artifacts_Organization_StatusKey");

                    b.HasIndex("OwnerOrganizationId", "Tla")
                        .IsUnique()
                        .HasDatabaseName("UX_Artifacts_Organization_Tla");

                    b.ToTable("Artifacts", "dbo");
                });

            modelBuilder.Entity("LagoVista.Relational.ArtifactInformationElementDTO", b =>
                {
                    b.Property<string>("ArtifactId")
                        .HasColumnType("varchar(32)")
                        .HasColumnOrder(1);

                    b.Property<string>("DefinitionId")
                        .HasColumnType("varchar(32)")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2(7)")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2(7)")
                        .HasColumnOrder(6);

                    b.Property<string>("OwnerOrganizationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnOrder(3);

                    b.Property<string>("UsageRole")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(4);

                    b.HasKey("ArtifactId", "DefinitionId");

                    b.HasIndex("DefinitionId")
                        .HasDatabaseName("IX_ArtifactInformationElements_DefinitionId");

                    b.HasIndex("OwnerOrganizationId")
                        .HasDatabaseName("IX_ArtifactInformationElements_OwnerOrganizationId");

                    b.HasIndex("OwnerOrganizationId", "ArtifactId")
                        .HasDatabaseName("IX_ArtifactInformationElements_Organization_ArtifactId");

                    b.HasIndex("OwnerOrganizationId", "DefinitionId")
                        .HasDatabaseName("IX_ArtifactInformationElements_Organization_DefinitionId");

                    b.ToTable("ArtifactInformationElements", "dbo");
                });

            modelBuilder.Entity("LagoVista.Relational.ConceptDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(32)")
                        .HasColumnOrder(1);

                    b.Property<string>("AliasesSerialized")
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("Aliases")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2(7)")
                        .HasColumnOrder(8);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnOrder(5);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2(7)")
                        .HasColumnOrder(9);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(4);

                    b.Property<string>("OwnerOrganizationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnOrder(2);

                    b.Property<string>("StatusKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("UX_Concepts_Key");

                    b.HasIndex("OwnerOrganizationId")
                        .HasDatabaseName("IX_Concepts_OwnerOrganizationId");

                    b.ToTable("Concepts", "dbo");
                });

            modelBuilder.Entity("LagoVista.Relational.DefinitionDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(32)")
                        .HasColumnOrder(1);

                    b.Property<string>("ConceptId")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2(7)")
                        .HasColumnOrder(13);

                    b.Property<string>("DefinitionSha256")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnOrder(12);

                    b.Property<string>("Example1")
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnOrder(8);

                    b.Property<string>("Example2")
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnOrder(9);

                    b.Property<string>("Example3")
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnOrder(10);

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2(7)")
                        .HasColumnOrder(14);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(6);

                    b.Property<string>("OwnerOrganizationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnOrder(2);

                    b.Property<string>("QualifiedKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasColumnOrder(5);

                    b.Property<string>("StatusKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(11);

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnOrder(3);

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.HasIndex("ConceptId")
                        .HasDatabaseName("IX_Definitions_ConceptId");

                    b.HasIndex("OwnerOrganizationId")
                        .HasDatabaseName("IX_Definitions_OwnerOrganizationId");

                    b.HasIndex("QualifiedKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Definitions_QualifiedKey");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("IX_Definitions_SubjectId");

                    b.ToTable("Definitions", "dbo");
                });

            modelBuilder.Entity("LagoVista.Relational.EmbeddingDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnOrder(3);

                    b.Property<int>("Dimensions")
                        .HasColumnType("int")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("GeneratedUtc")
                        .HasColumnType("datetime2(7)")
                        .HasColumnOrder(8);

                    b.Property<string>("ModelKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasColumnOrder(4);

                    b.Property<string>("OwnerOrganizationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnOrder(2);

                    b.Property<string>("SourceSha256")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnOrder(6);

                    b.Property<byte[]>("Vector")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.HasIndex("OwnerOrganizationId")
                        .HasDatabaseName("IX_Embeddings_OwnerOrganizationId");

                    b.HasIndex("SourceSha256")
                        .HasDatabaseName("IX_Embeddings_SourceSha256");

                    b.HasIndex("DefinitionId", "ModelKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Embeddings_DefinitionId_ModelKey");

                    b.ToTable("Embeddings", "dbo");
                });

            modelBuilder.Entity("LagoVista.Relational.SemanticDefinitionViewDTO", b =>
                {
                    b.Property<string>("ConceptDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConceptId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConceptKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConceptName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefinitionSha256")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Example1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Example2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Example3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerOrganizationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualifiedKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("usv_SemanticDefinitions", "dbo");
                });

            modelBuilder.Entity("LagoVista.Relational.SemanticRegistryDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2(7)")
                        .HasColumnOrder(7);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(3);

                    b.Property<string>("OwnerOrganizationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnOrder(2);

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnOrder(4);

                    b.Property<long?>("SeededFromRevision")
                        .HasColumnType("bigint")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("SeededUtc")
                        .HasColumnType("datetime2(7)")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2(7)")
                        .HasColumnOrder(8);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Registry_Name");

                    b.HasIndex("OwnerOrganizationId")
                        .HasDatabaseName("IX_Registry_OwnerOrganizationId");

                    b.ToTable("Registry", "dbo");
                });

            modelBuilder.Entity("LagoVista.Relational.SubjectDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(32)")
                        .HasColumnOrder(1);

                    b.Property<string>("AliasesSerialized")
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("Aliases")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2(7)")
                        .HasColumnOrder(8);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnOrder(5);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2(7)")
                        .HasColumnOrder(9);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(4);

                    b.Property<string>("OwnerOrganizationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnOrder(2);

                    b.Property<string>("StatusKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("UX_Subjects_Key");

                    b.HasIndex("OwnerOrganizationId")
                        .HasDatabaseName("IX_Subjects_OwnerOrganizationId");

                    b.ToTable("Subjects", "dbo");
                });

            modelBuilder.Entity("LagoVista.Relational.ArtifactInformationElementDTO", b =>
                {
                    b.HasOne("LagoVista.Relational.ArtifactDTO", null)
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LagoVista.Relational.DefinitionDTO", null)
                        .WithMany()
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LagoVista.Relational.DefinitionDTO", b =>
                {
                    b.HasOne("LagoVista.Relational.ConceptDTO", null)
                        .WithMany()
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LagoVista.Relational.SubjectDTO", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LagoVista.Relational.EmbeddingDTO", b =>
                {
                    b.HasOne("LagoVista.Relational.DefinitionDTO", null)
                        .WithMany()
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
