<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CassandraCSharpDriver" />
    <PackageReference Include="LagoVista.Core.TestBase" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LagoVista.CloudStorage\LagoVista.CloudStorage.csproj" />
  </ItemGroup>

</Project>
