$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "EntityUtilsRepository"
Write-Host "====================="
Write-Host "Status: IN PROGRESS"
Write-Host "Provider-neutral read primitives are in place for by-type, by-id, and count queries."
Write-Host "Repository wiring and parity coverage are next; mutation/patch behavior remains Cosmos-backed for now."
Write-Host ""
& (Join-Path $PSScriptRoot "audit-cosmos-consumers.ps1") -Scope Application -FileContains "EntityUtilsRepository.cs"
