<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LagoVista.Core" />
    <PackageReference Include="LagoVista.Core.Configuration" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Converters\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LagoVista.CloudStorage\LagoVista.CloudStorage.csproj" />
  </ItemGroup>
  
</Project>
